{% set name = "bmi_wrap" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

source:
  path: ..

requirements:
  build:
    - setuptools

  host:
    - python

  run:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - python
    - cython
    - numpy 1.11.*
    - pyyaml
    - jinja2
    - cookiecutter
    - six
    - scripting

test:
  imports:
    - bmi_wrap
  commands:
    - bmi-wrap -h

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
