language: generic
os:
- linux
- osx
env:
  matrix:
  - PYTHON="3.8"
sudo: false

jobs:
  include:
  - stage: lint
    os: linux
    script:
    - pip install flake8
    - make lint

  - stage: docs
    os: linux
    install:
    - pip install -r requirements-docs.txt
    - pip install -e .
    script:
    - make -C docs clean html

before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > $HOME/miniconda.sh
  else
    curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh > $HOME/miniconda.sh
  fi
- bash $HOME/miniconda.sh -b -p $(pwd)/anaconda
- export PATH="$(pwd)/anaconda/bin:$PATH"
- conda init bash
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    source $HOME/.bash_profile
  else
    source $HOME/.bashrc
  fi
- conda install mamba --yes -c conda-forge
- mamba install python=$PYTHON --yes -c conda-forge
- mamba install bmi-c bmi-fortran cmake pkg-config fortran-compiler c-compiler libgfortran --yes -c conda-forge
- |
  mkdir _build \
  && pushd _build \
  &&   cmake ../external/bmi-example-c -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
  &&   make install \
  &&   popd
- |
  mkdir _buildf \
  && pushd _buildf \
  &&   cmake ../external/bmi-example-fortran -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
  &&   make install \
  &&   popd
install:
- mamba install --file=requirements-testing.txt --yes -c conda-forge
- pip install .
script:
- babelize --version
- babelize --help
- babelize init --help
- babelize update --help
- babelize generate --help
- babelize generate - --no-input
- python -c 'import babelizer; print(babelizer.__version__)'
- pytest -vvv
