environment:

  global:
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\ci\\build.cmd"

  matrix:

    - PYTHON: "3.8"
      MINICONDA: C:\\Miniconda38-x64

platform:
  - x64

image: Visual Studio 2019

init:
  - "ECHO %PYTHON% %HOME% %PLATFORM%"
  - "ECHO %APPVEYOR_REPO_BRANCH%"

install:
  - cmd: call %MINICONDA%\Scripts\activate.bat
  - cmd: conda install mamba -c conda-forge --yes
  - cmd: mamba config --set always_yes yes
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: mamba list
  - cmd: python --version

build: false

test_script:
  - cmd: pip install -e .
  - cmd: babelize --version
  - cmd: babelize --help
  - cmd: babelize init --help
  - cmd: babelize update --help
  - cmd: babelize generate --help
  - cmd: babelize generate - --no-input
