{{"{"}}% set name = "pymt_{{cookiecutter.module_name}}" %{{"}"}}
{{"{"}}% set version = "0.1" %{{"}"}}
{{"{"}}% set build = "0" %{{"}"}}

package:
  name: {{"{{"}} name {{"}}"}}
  version: {{"{{"}} version {{"}}"}}

source:
  path: ..

build:
  number: {{"{{"}} build {{"}}"}}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - numpy 1.11.*
    - cython
    - model_metadata
    - {{cookiecutter.module_name}}

  run:
    - python
    - setuptools
    - pymt
    - {{cookiecutter.module_name}}

test:
  requires:
    - bmi-tester
  imports:
    - pymt
    - {{cookiecutter.module_name}}
  commands:
    - mmd-stage {{cookiecutter.class_name}} .
    - bmi-test {{cookiecutter.module_name}}:{{cookiecutter.class_name}} --infile={{cookiecutter.module_name}}.txt

about:
  summary: Python package that wraps the {{cookiecutter.module_name}} BMI.
  home: https://github.com/mcflugen/pymt_{{cookiecutter.module_name}}
  license: {{cookiecutter.open_source_license}}
  license_file: LICENSE
  dev_url: https://github.com/mcflugen/pymt_{{cookiecutter.module_name}}
