{{"{%"}} set data = load_setup_py_data() {{"%}"}}

package:
  name: "pymt_{{cookiecutter.plugin_name}}"
  version: {{"{{"}} data.get('version') {{"}}"}}

source:
  path: ..

build:
  number: 0
  script: "{{"{{"}} PYTHON {{"}}"}} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{"{{"}} compiler('c') {{"}}"}}
  host:
    - python
    - pip
    - cython
    - numpy 1.11.*
    - model_metadata
    {%- if cookiecutter.plugin_requirements -%}
    {%- for requirement in cookiecutter.plugin_requirements.split(',') %}
    - {{ requirement|trim }} {% endfor %}
    {%- endif %}

  run:
    - python
    - {{"{{"}} pin_compatible('numpy') {{"}}"}}
    {%- if cookiecutter.plugin_requirements -%}
    {%- for requirement in cookiecutter.plugin_requirements.split(',') %}
    - {{ requirement|trim }} {% endfor %}
    {%- endif %}

test:
  requires:
    - bmi-tester
    - model_metadata
  imports:
    - pymt_{{cookiecutter.plugin_name}}
  commands:
{%- for entry_point in cookiecutter.entry_points.split(',') %}
    {%- set plugin_module, plugin_class = entry_point.split('=')[1].split(':') -%}
    {%- if cookiecutter.language == 'c' or cookiecutter.language == 'c++' %}
        {%- set plugin_class = entry_point.split('=')[0] -%}
    {%- endif %}
    - config_file=$(mmd-stage {{ plugin_class }} . > MANIFEST && mmd-query {{ plugin_class }} --var=run.config_file.path)
    - bmi-test pymt_{{ cookiecutter.plugin_name }}.bmi:{{ plugin_class }} --infile=$config_file --manifest=MANIFEST -v
{%- endfor %}

about:
  summary: Python package that wraps the {{cookiecutter.plugin_name}} BMI.
  home: https://github.com/mcflugen/pymt_{{cookiecutter.plugin_name}}
  license: {{cookiecutter.open_source_license}}
  license_file: LICENSE
  dev_url: https://github.com/mcflugen/pymt_{{cookiecutter.plugin_name}}
