name: Build/Test CI

on: [push, pull_request]

jobs:
  build-and-test:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge
          channel-priority: true

      - name: Install dependencies
        run: |
          pip install coverage[toml]
          mamba install --file=requirements.txt --file=requirements-testing.txt --file=external/requirements.txt
          conda list

      - name: Install babelizer
        run: |
          pip install .

      - name: Run diagnostics
        run: |
          babelize --version
          babelize --help
          babelize init --help
          babelize update --help
          babelize generate --help
          babelize generate
          python -c 'import babelizer; print(babelizer.__version__)'

      - name: Make C example
        run: |
          mkdir buildc && pushd buildc
          cmake ../external/bmi-example-c -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
          make install
          popd

      - name: Make C++ example
        run: |
          mkdir buildcxx && pushd buildcxx
          cmake ../external/bmi-example-cxx -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
          make install
          popd

      - name: Make Fortran example
        run: |
          mkdir buildf && pushd buildf
          cmake ../external/bmi-example-fortran -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
          make install
          popd

      - name: Make Python example
        run: |
          pushd ./external/bmi-example-python
          make install
          popd

      - name: Test babelizer + language examples and generate coverage report
        run: |
          pytest --cov=babelizer --cov-report=xml:./coverage.xml -vvv babelizer tests external/tests

      - name: Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9'
        uses: AndreMiras/coveralls-python-action@v20201129
