name: Build/Test CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge
          channel-priority: true

      - name: Install dependencies
        run: |
          mamba install --file=requirements.txt --file=requirements-testing.txt
          conda list

      - name: Install babelizer
        run: |
          pip install .

      - name: Diagnostics
        run: |
          babelize --version
          babelize --help
          babelize init --help
          babelize update --help
          babelize generate --help
          babelize generate - --no-input
          python -c 'import babelizer; print(babelizer.__version__)'
