name: Build/Test CI

on: [push, pull_request]

jobs:
  build-and-test:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]
        language: ["c", "cxx", "python", "fortran"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge
          channel-priority: true

      - name: Install dependencies
        run: python -m pip install nox tomli

      - name: Install compilers
        run: mamba install c-compiler cxx-compiler fortran-compiler cmake

      - name: Run the language tests
        run: nox -s "test-langs-${{ matrix.python-version }}(lang='${{ matrix.language }}')" --python ${{ matrix.python-version }} --verbose

      - name: Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9'
        uses: AndreMiras/coveralls-python-action@v20201129
